version: '3'

services:
    dbproject:
        image: benhamohamed/testci20_db:2.0
        ports:
        - 9090:8080
        depends_on:
        - db
    db:
        image: benhamohamed/testci30_db:3.0
        ports:
        - 5432:5432
        volumes:
        - dbdata:/var/lib/postgresql/data
volumes:
    dbdata: